version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file: [.env]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ:-America/Phoenix}
      PGTZ: ${PGTZ:-America/Phoenix}
      # expects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB in .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: place .sql/.sh files here to auto-run on first start
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
